################################################################################
# 自动生成的文件。不要编辑！
################################################################################

-include ../makefile.init

RM := rm -rf

# All of the sources participating in the build are defined here
-include sources.mk
-include rt-thread/src/subdir.mk
-include rt-thread/libcpu/arm/common/subdir.mk
-include rt-thread/libcpu/arm/arm926/subdir.mk
-include rt-thread/components/utilities/utest/subdir.mk
-include rt-thread/components/utilities/ulog/backend/subdir.mk
-include rt-thread/components/utilities/ulog/subdir.mk
-include rt-thread/components/net/sal/src/subdir.mk
-include rt-thread/components/net/sal/socket/subdir.mk
-include rt-thread/components/net/sal/impl/subdir.mk
-include rt-thread/components/net/sal/dfs_net/subdir.mk
-include rt-thread/components/net/netdev/src/subdir.mk
-include rt-thread/components/net/lwip/port/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/netif/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/core/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/apps/ping/subdir.mk
-include rt-thread/components/net/lwip/lwip-2.0.3/src/api/subdir.mk
-include rt-thread/components/libc/posix/io/poll/subdir.mk
-include rt-thread/components/libc/compilers/newlib/subdir.mk
-include rt-thread/components/libc/compilers/common/subdir.mk
-include rt-thread/components/finsh/subdir.mk
-include rt-thread/components/fal/src/subdir.mk
-include rt-thread/components/fal/samples/porting/subdir.mk
-include rt-thread/components/drivers/watchdog/subdir.mk
-include rt-thread/components/drivers/usb/usbhost/core/subdir.mk
-include rt-thread/components/drivers/usb/usbhost/class/subdir.mk
-include rt-thread/components/drivers/usb/usbdevice/core/subdir.mk
-include rt-thread/components/drivers/usb/usbdevice/class/subdir.mk
-include rt-thread/components/drivers/touch/subdir.mk
-include rt-thread/components/drivers/spi/sfud/src/subdir.mk
-include rt-thread/components/drivers/spi/subdir.mk
-include rt-thread/components/drivers/serial/subdir.mk
-include rt-thread/components/drivers/rtc/subdir.mk
-include rt-thread/components/drivers/misc/subdir.mk
-include rt-thread/components/drivers/ipc/subdir.mk
-include rt-thread/components/drivers/i2c/subdir.mk
-include rt-thread/components/drivers/hwtimer/subdir.mk
-include rt-thread/components/drivers/can/subdir.mk
-include rt-thread/components/drivers/audio/subdir.mk
-include rt-thread/components/dfs/src/subdir.mk
-include rt-thread/components/dfs/filesystems/elmfat/subdir.mk
-include rt-thread/components/dfs/filesystems/devfs/subdir.mk
-include packages/sqlite-v3.19.3/subdir.mk
-include packages/ramdisk-latest/src/subdir.mk
-include packages/LVGL-v8.2.0/src/widgets/subdir.mk
-include packages/LVGL-v8.2.0/src/misc/subdir.mk
-include packages/LVGL-v8.2.0/src/hal/subdir.mk
-include packages/LVGL-v8.2.0/src/font/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/win/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/tileview/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/tabview/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/spinner/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/spinbox/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/span/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/msgbox/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/meter/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/menu/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/list/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/led/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/keyboard/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/imgbtn/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/colorwheel/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/chart/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/calendar/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/widgets/animimg/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/themes/mono/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/themes/default/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/themes/basic/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/others/snapshot/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/others/monkey/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/others/gridnav/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/sjpg/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/rlottie/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/qrcode/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/png/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/gif/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/fsdrv/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/freetype/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/ffmpeg/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/libs/bmp/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/layouts/grid/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/layouts/flex/subdir.mk
-include packages/LVGL-v8.2.0/src/extra/subdir.mk
-include packages/LVGL-v8.2.0/src/draw/sw/subdir.mk
-include packages/LVGL-v8.2.0/src/draw/stm32_dma2d/subdir.mk
-include packages/LVGL-v8.2.0/src/draw/sdl/subdir.mk
-include packages/LVGL-v8.2.0/src/draw/nxp_vglite/subdir.mk
-include packages/LVGL-v8.2.0/src/draw/nxp_pxp/subdir.mk
-include packages/LVGL-v8.2.0/src/draw/subdir.mk
-include packages/LVGL-v8.2.0/src/core/subdir.mk
-include packages/LVGL-v8.2.0/env_support/rt-thread/subdir.mk
-include libraries/nu_packages/AudioCodec/subdir.mk
-include libraries/nu_packages/ADC_TOUCH/subdir.mk
-include libraries/n9h30/rtt_port/subdir.mk
-include libraries/n9h30/UsbHostLib/src/subdir.mk
-include libraries/n9h30/Driver/Source/subdir.mk
-include board/subdir.mk
-include applications/lvgl/subdir.mk
-include applications/subdir.mk
-include subdir.mk
-include objects.mk

ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(ASM_DEPS)),)
-include $(ASM_DEPS)
endif
ifneq ($(strip $(S_DEPS)),)
-include $(S_DEPS)
endif
ifneq ($(strip $(S_UPPER_DEPS)),)
-include $(S_UPPER_DEPS)
endif
ifneq ($(strip $(C_DEPS)),)
-include $(C_DEPS)
endif
endif

-include ../makefile.defs

# Add inputs and outputs from these tool invocations to the build variables 
SECONDARY_FLASH += \
rtthread.bin \

SECONDARY_SIZE += \
rtthread.siz \


# 所有目标
all: rtthread.elf secondary-outputs

# 工具调用
rtthread.elf: $(OBJS) $(USER_OBJS)
	arm-none-eabi-gcc -T "D:\RT-ThreadStudio\workspace\ComponentsLib\linking_scripts\n9h30.ld" -Xlinker --gc-sections -Wl,-Map,"rtthread.map" -Xlinker --cref -mcpu=arm926ej-s -Wl,--gc-sections,-cref,-Map=rtthread_n9h30.map -o "rtthread.elf" $(OBJS) $(USER_OBJS) $(LIBS)

rtthread.bin: rtthread.elf
	arm-none-eabi-objcopy -O binary "rtthread.elf"  "rtthread.bin"

rtthread.siz: rtthread.elf
	arm-none-eabi-size --format=berkeley "rtthread.elf"

# 其他目标
clean:
	-$(RM) $(OBJS)$(SECONDARY_FLASH)$(SECONDARY_SIZE)$(ASM_DEPS)$(S_DEPS)$(S_UPPER_DEPS)$(C_DEPS) rtthread.elf
	-@echo ' '

secondary-outputs: $(SECONDARY_FLASH) $(SECONDARY_SIZE)

.PHONY: all clean dependents

-include ../makefile.targets
